"""w3

Revision ID: 89abdd4450f4
Revises: 90caae053056
Create Date: 2026-01-11 06:08:37.660251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89abdd4450f4'
down_revision = '90caae053056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
