"""sdf

Revision ID: 115b465a0229
Revises: e06f09bd637d
Create Date: 2026-01-14 15:59:46.175796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b465a0229'
down_revision = 'e06f09bd637d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_constraint('orders_iiko_order_id_key', 'orders', type_='unique')
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.drop_index('ix_orders_iiko_order_id', table_name='orders')
    op.create_index(op.f('ix_orders_iiko_order_id'), 'orders', ['iiko_order_id'], unique=True)
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.drop_index(op.f('ix_orders_iiko_order_id'), table_name='orders')
    op.create_index('ix_orders_iiko_order_id', 'orders', ['iiko_order_id'], unique=False)
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.create_unique_constraint('orders_iiko_order_id_key', 'orders', ['iiko_order_id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
